on:
  schedule:
    - cron:  '0 8 * * *'
name: Daily Build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        node: [ '12', '10' ]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn audit
    - run: yarn lint
    - run: yarn compile
    - run: yarn test
